name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
          fetch-depth: 1
    - name: cd src
      run: cd src
    - name: ls
      run: ls
    - name: cd src && make
      run: make all
    - name: ls
      run: ls
    - name: make check
      run: make check
    - name: make run
      run: make run
    - name: make clean
      run: make clean
      
