name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
          fetch-depth: 1
    - name: Run make
      run: cd src && make
    - name: Clean up files
      run: make clean
      
